{{- if ne .Values.namespace .Release.Namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app: hostpath-provisioner
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- end }}
