apiVersion: v2
name: multus
description: Multus CNI with thick plugin and dynamic networks controller for KubeVirt
type: application
version: "0.1.0"
appVersion: "4.1.4"
kubeVersion: ">=1.30.0-0"
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
  - https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller
