---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-operator
  namespace: {{ .Values.namespace }}
  labels:
    app: forklift
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- include "kubevirt-stack.imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-api
  namespace: {{ .Values.namespace }}
  labels:
    app: forklift
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-controller
  namespace: {{ .Values.namespace }}
  labels:
    app: forklift
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forklift-populator-controller
  namespace: {{ .Values.namespace }}
  labels:
    app: forklift
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
