---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aaq-operator-cluster
  labels:
    operator.aaq.kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - customresourcedefinitions/status
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - aaqs
  - aaqs/finalizers
  verbs:
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - aaqs/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - update
  - list
  - watch
  - create
  - get
  - delete
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - update
  - list
  - watch
  - get
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - aaqjobqueueconfigs
  verbs:
  - get
  - watch
  - list
  - create
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - aaqjobqueueconfigs/status
  verbs:
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareresourcequotas
  verbs:
  - get
  - update
  - watch
  - list
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareclusterresourcequotas
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareappliedclusterresourcequotas
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareclusterresourcequotas/finalizers
  verbs:
  - create
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareresourcequotas/finalizers
  verbs:
  - create
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareresourcequotas/status
  verbs:
  - update
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - applicationawareclusterresourcequotas/status
  verbs:
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - kubevirts
  verbs:
  - list
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  - virtualmachineinstancemigrations
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - delete
- apiGroups:
  - aaq.kubevirt.io
  resources:
  - aaqs
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - create
- apiGroups:
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aaq-operator
  labels:
    operator.aaq.kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aaq-operator-cluster
subjects:
  - kind: ServiceAccount
    name: aaq-operator
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aaq-operator
  namespace: {{ .Values.namespace }}
  labels:
    operator.aaq.kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - configmaps
  - events
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  - prometheusrules
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - delete
  - update
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aaq-operator
  namespace: {{ .Values.namespace }}
  labels:
    operator.aaq.kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aaq-operator
subjects:
  - kind: ServiceAccount
    name: aaq-operator
    namespace: {{ .Values.namespace }}
