---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-provider-kubevirt
  namespace: {{ .Values.namespace }}
  labels:
    app: cloud-provider-kubevirt
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
