---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-console-proxy-config
  namespace: {{ include "kubevirt-stack.namespace" . }}
  labels:
    app: vm-console-proxy
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
data:
  config.yaml: |
    tokenGenerationService:
      enabled: true
