---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-console-proxy
  namespace: {{ include "kubevirt-stack.namespace" . }}
  labels:
    app: vm-console-proxy
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
