---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-ipam-controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    app: ipam-virt-workloads
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- include "kubevirt-stack.imagePullSecrets" . }}
