apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdi-operator
  namespace: {{ .Values.namespace }}
  labels:
    operator.cdi.kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- include "kubevirt-stack.imagePullSecrets" . }}
