apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-operator
  namespace: {{ include "kubevirt-stack.namespace" . }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
{{- include "kubevirt-stack.imagePullSecrets" . }}
