apiVersion: v1
kind: ConfigMap
metadata:
  name: whereabouts-config
  namespace: {{ include "kubevirt-stack.namespace" . }}
  labels:
    {{- include "kubevirt-stack.labels" . | nindent 4 }}
data:
  cron-expression: {{ .Values.cronExpression | quote }}
